-- MYSQL Script by MYSQL
-- Mon May 28 10:28:28 2018
-- Model: New Model    Version: 1.0
-- MYSQL Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema moto10racingHBT
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moto10racingHBT` ;

-- -----------------------------------------------------
-- Schema moto10racingHBT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moto10racingHBT` DEFAULT CHARACTER SET latin1 ;
USE `moto10racingHBT` ;

-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Categoria` (
  `idCategoria` INT(30) NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `descripcionCategoria` LONGTEXT CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;

--
-- Dumping data for table `Categoria`
--

LOCK TABLES `Categoria` WRITE;
/*!40000 ALTER TABLE `Categoria` DISABLE KEYS */;
INSERT INTO `Categoria` VALUES (1,'DEFAULT','DEFAULT');
/*!40000 ALTER TABLE `Categoria` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Ciudad` (
  `idCiudad` INT(30) NOT NULL AUTO_INCREMENT,
  `nombreCiudad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCiudad`),
  UNIQUE INDEX `nombreCiudad_UNIQUE` (`nombreCiudad` ASC),
  UNIQUE INDEX `idCiudad_UNIQUE` (`idCiudad` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1063
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `Ciudad`
--

LOCK TABLES `Ciudad` WRITE;
/*!40000 ALTER TABLE `Ciudad` DISABLE KEYS */;
INSERT INTO `Ciudad` VALUES (1,'CUMARIBO'),(2,'SANTA ROSALÍA'),(3,'LA PRIMAVERA'),(4,'PUERTO CARREÑO'),(5,'YAVARATÉ'),(6,'TARAIRA'),(7,'PACOA'),(8,'CARURÚ'),(9,'MITÚ'),(10,'MIRAFLORES-GUAVIARE'),(11,'EL RETORNO'),(12,'CALAMAR-GUAVIARE'),(13,'SAN JOSÉ DEL GUAVIARE'),(14,'CACAHUAL'),(15,'LA GUADALUPE-GUAINIA'),(16,'PUERTO COLOMBIA-GUAINIA'),(17,'SAN FELIPE'),(18,'MAPIRIPANA'),(19,'BARRANCO MINAS'),(20,'INÍRIDA'),(21,'TARAPACÁ'),(22,'PUERTO SANTANDER-GUIANIA'),(23,'PUERTO NARIÑO'),(24,'PUERTO ARICA'),(25,'PUERTO ALEGRÍA'),(26,'LA PEDRERA'),(27,'LA CHORRERA'),(28,'EL ENCANTO'),(29,'LETICIA'),(30,'PROVIDENCIA-SAN ANDRÉS'),(31,'SAN ANDRÉS-ARCHIPIELAGO'),(32,'VILLAGARZÓN'),(33,'SANTIAGO-META'),(34,'SAN FRANCISCO'),(35,'SIBUNDOY'),(36,'PUERTO LEGUÍZAMO'),(37,'PUERTO GUZMÁN'),(38,'PUERTO CAICEDO'),(39,'PUERTO ASÍS'),(40,'ORITO'),(41,'COLÓN'),(42,'MOCOA'),(43,'VILLANUEVA-PUTUMAYO'),(44,'TRINIDAD'),(45,'TAURAMENA'),(46,'TÁMARA'),(47,'SAN LUIS DE PALENQUE'),(48,'SÁCAMA'),(49,'SABANALARGA-ARAUCA'),(50,'RECETOR'),(51,'PORE'),(52,'PAZ DE ARIPORO'),(53,'OROCUÉ'),(54,'NUNCHÍA'),(55,'MONTERREY'),(56,'MANÍ'),(57,'LA SALINA'),(58,'HATO COROZAL'),(59,'CHÁMEZA'),(60,'AGUAZUL'),(61,'YOPAL'),(62,'TAME'),(63,'SARAVENA'),(64,'PUERTO RONDÓN'),(65,'FORTUL'),(66,'CRAVO NORTE'),(67,'ARAUQUITA'),(68,'ARAUCA'),(69,'ZARZAL'),(70,'YUMBO'),(71,'YOTOCO'),(72,'VIJES'),(73,'VERSALLES'),(74,'ULLOA'),(75,'TULUÁ'),(76,'TRUJILLO'),(77,'TORO'),(78,'SEVILLA'),(79,'SAN PEDRO-VALLE DEL CAUCA'),(80,'ROLDANILLO'),(81,'RIOFRÍO'),(82,'RESTREPO-VALLE DEL CAUCA'),(83,'PRADERA'),(84,'PALMIRA'),(85,'OBANDO'),(86,'LA VICTORIA-VALLE DEL CAUCA'),(87,'LA UNIÓN-VALLE DEL CAUCA'),(88,'LA CUMBRE'),(89,'JAMUNDÍ'),(90,'GUACARÍ'),(91,'GINEBRA'),(92,'FLORIDA'),(93,'EL DOVIO'),(94,'EL CERRITO'),(95,'EL CAIRO'),(96,'EL ÁGUILA'),(97,'DAGUA'),(98,'CARTAGO'),(99,'CANDELARIA-VALLE DEL CAUCA'),(100,'CAICEDONIA'),(101,'BUGALAGRANDE'),(102,'GUADALAJARA DE BUGA'),(103,'BUENAVENTURA'),(104,'BOLÍVAR-VALLE DEL CAUCA'),(105,'ARGELIA-VALLE DEL CAUCA'),(106,'ANSERMANUEVO'),(107,'ANDALUCÍA'),(108,'ALCALÁ'),(109,'VILLARRICA'),(110,'VILLAHERMOSA'),(111,'VENADILLO'),(112,'VALLE DE SAN JUAN'),(113,'SUÁREZ-TOLIMA'),(114,'SANTA ISABEL'),(115,'SAN EFREN-TOLIMA'),(116,'SAN ANTONIO'),(117,'SALDAÑA'),(118,'ROVIRA'),(119,'RONCESVALLES'),(120,'RIOBLANCO'),(121,'PURIFICACIÓN'),(122,'PRADO'),(123,'PLANADAS'),(124,'PIEDRAS'),(125,'PALOCABILDO'),(126,'ORTEGA'),(127,'NATAGAIMA'),(128,'MURILLO'),(129,'MELGAR'),(130,'SAN SEBASTIÁN DE MARIQUITA'),(131,'LÍBANO'),(132,'LÉRIDA'),(133,'ICONONZO'),(134,'HONDA'),(135,'HERVEO'),(136,'GUAMO'),(137,'FRESNO'),(138,'FLANDES'),(139,'FALAN'),(140,'ESPINAL'),(141,'DOLORES'),(142,'CUNDAY'),(143,'COYAIMA'),(144,'COELLO'),(145,'CHAPARRAL'),(146,'CASABIANCA'),(147,'CARMEN DE APICALÁ'),(148,'CAJAMARCA'),(149,'ATACO'),(150,'ANZOÁTEGUI'),(151,'AMBALEMA'),(152,'ALVARADO'),(153,'ALPUJARRA'),(154,'IBAGUÉ'),(155,'TOLÚ VIEJO'),(156,'SANTIAGO DE TOLÚ'),(157,'SUCRE-SUCRE'),(158,'SAN PEDRO-SUCRE'),(159,'SAN ONOFRE'),(160,'SAN MARCOS'),(161,'SAN BENITO ABAD'),(162,'SAMPUÉS'),(163,'PALMITO'),(164,'OVEJAS'),(165,'MORROA'),(166,'MAJAGUAL'),(167,'LOS PALMITOS'),(168,'LA UNIÓN-SUCRE'),(169,'GUARANDA'),(170,'GALERAS'),(171,'EL ROBLE'),(172,'CHALÁN'),(173,'COVEÑAS'),(174,'COROZAL'),(175,'CAIMITO'),(176,'BUENAVISTA-GUAJIRA'),(177,'SINCELEJO'),(178,'ZAPATOCA'),(179,'VILLANUEVA-SUCRE'),(180,'VETAS'),(181,'VÉLEZ'),(182,'VALLE DE SAN JOSÉ'),(183,'TONA'),(184,'SURATÁ'),(185,'SUCRE-SANTANDER'),(186,'SUAITA'),(187,'SOCORRO'),(188,'SIMACOTA'),(189,'SANTA HELENA DEL OPÓN'),(190,'SANTA BÁRBARA-SANTANDER'),(191,'SAN VICENTE DE CHUCURÍ'),(192,'SAN MIGUEL'),(193,'SAN JOSÉ DE MIRANDA'),(194,'SAN JOAQUÍN'),(195,'SAN GIL'),(196,'SAN BENITO I'),(197,'SAN BENITO II'),(198,'SAN ANDRÉS-SANTANDER'),(199,'SABANA DE TORRES'),(200,'RIONEGRO-SANTANDER'),(201,'PUERTO WILCHES'),(202,'PUERTO PARRA'),(203,'PUENTE NACIONAL'),(204,'PINCHOTE'),(205,'PIEDECUESTA'),(206,'PÁRAMO'),(207,'PALMAS DEL SOCORRO'),(208,'PALMAR'),(209,'ONZAGA'),(210,'OIBA'),(211,'OCAMONTE'),(212,'MOLAGAVITA'),(213,'MOGOTES'),(214,'MATANZA'),(215,'MÁLAGA'),(216,'MACARAVITA'),(217,'LOS SANTOS'),(218,'LEBRIJA'),(219,'LA PAZ'),(220,'LANDÁZURI'),(221,'LA BELLEZA'),(222,'JESÚS MARÍA'),(223,'HATO'),(224,'GÜEPSA'),(225,'GUAVATÁ'),(226,'GUAPOTÁ'),(227,'GUADALUPE-SANTANDER'),(228,'GUACA'),(229,'GIRÓN'),(230,'GÁMBITA'),(231,'GALÁN'),(232,'FLORIDABLANCA'),(233,'FLORIÁN'),(234,'ENCISO'),(235,'ENCINO'),(236,'EL PLAYÓN'),(237,'EL PEÑÓN-SANTANDER'),(238,'EL GUACAMAYO'),(239,'EL CARMEN DE CHUCURÍ'),(240,'CURITÍ'),(241,'COROMORO'),(242,'CONTRATACIÓN'),(243,'CONFINES'),(244,'CONCEPCIÓN-SANTANDER'),(245,'CIMITARRA'),(246,'CHIPATÁ'),(247,'CHIMA-SANTANDER'),(248,'CHARTA'),(249,'CHARALÁ'),(250,'CERRITO'),(251,'CEPITÁ'),(252,'CARCASÍ'),(253,'CAPITANEJO'),(254,'CALIFORNIA'),(255,'CABRERA-SANTANDER'),(256,'BOLÍVAR-SANTANDER'),(257,'BETULIA-SANTANDER'),(258,'BARRANCABERMEJA'),(259,'BARICHARA'),(260,'BARBOSA-SANTANDER'),(261,'ARATOCA'),(262,'ALBANIA-SANTANDER'),(263,'AGUADA'),(264,'BUCARAMANGA'),(265,'SANTUARIO'),(266,'SANTA ROSA DE CABAL'),(267,'QUINCHÍA'),(268,'PUEBLO RICO'),(269,'MISTRATÓ'),(270,'MARSELLA'),(271,'LA VIRGINIA'),(272,'LA CELIA'),(273,'GUÁTICA'),(274,'DOSQUEBRADAS'),(275,'BELÉN DE UMBRÍA'),(276,'BALBOA-RISARALDA'),(277,'APÍA'),(278,'PEREIRA'),(279,'SALENTO'),(280,'QUIMBAYA'),(281,'PIJAO'),(282,'MONTENEGRO'),(283,'LA TEBAIDA'),(284,'GÉNOVA'),(285,'FILANDIA'),(286,'CÓRDOBA-QUINDIO'),(287,'CIRCASIA'),(288,'CALARCÁ'),(289,'BUENAVISTA-QUINDIO'),(290,'ARMENIA'),(291,'VILLA DEL ROSARIO'),(292,'VILLA CARO'),(293,'TOLEDO-QUINDIO'),(294,'TIBÚ'),(295,'TEORAMA'),(296,'SILOS'),(297,'SARDINATA'),(298,'SANTIAGO-QUINDIO'),(299,'SAN CAYETANO'),(300,'SAN CALIXTO'),(301,'SALAZAR'),(302,'RAGONVALIA'),(303,'PUERTO SANTANDER-QUINDIO'),(304,'PAMPLONITA'),(305,'PAMPLONA'),(306,'OCAÑA'),(307,'MUTISCUA'),(308,'LOURDES'),(309,'LOS PATIOS'),(310,'LA PLAYA'),(311,'LA ESPERANZA'),(312,'LABATECA'),(313,'HERRÁN'),(314,'HACARÍ'),(315,'GRAMALOTE'),(316,'EL ZULIA'),(317,'EL TARRA'),(318,'EL CARMEN'),(319,'DURANIA'),(320,'CUCUTILLA'),(321,'CONVENCIÓN'),(322,'CHITAGÁ'),(323,'CHINÁCOTA'),(324,'CÁCHIRA'),(325,'CÁCOTA'),(326,'BUCARASICA'),(327,'BOCHALEMA'),(328,'ARBOLEDAS'),(329,'ÁBREGO'),(330,'CÚCUTA'),(331,'YACUANQUER'),(332,'TÚQUERRES'),(333,'TANGUA'),(334,'TAMINANGO'),(335,'SAPUYES'),(336,'SAN PEDRO DE CARTAGO'),(337,'SAN PABLO-NARIÑO'),(338,'SAN LORENZO'),(339,'SAN BERNARDO-NARIÑO'),(340,'SANDONÁ'),(341,'SAMANIEGO'),(342,'RICAURTE-NARIÑO'),(343,'PUPIALES'),(344,'PUERRES'),(345,'PROVIDENCIA-NARIÑO'),(346,'POTOSÍ'),(347,'POLICARPA'),(348,'OSPINA'),(349,'NARIÑO-NARIÑO'),(350,'MOSQUERA-NARIÑO'),(351,'LINARES'),(352,'LEIVA'),(353,'LA UNIÓN-NARIÑO'),(354,'LA TOLA'),(355,'LA LLANADA'),(356,'LA FLORIDA'),(357,'LA CRUZ'),(358,'IPIALES'),(359,'IMUÉS'),(360,'ILES'),(361,'GUALMATÁN'),(362,'GUAITARILLA'),(363,'GUACHUCAL'),(364,'FUNES'),(365,'EL TAMBO-NARIÑO'),(366,'EL TABLÓN DE GÓMEZ'),(367,'EL ROSARIO'),(368,'EL PEÑOL-NARIÑO'),(369,'EL CHARCO'),(370,'CHACHAGÜÍ'),(371,'CUMBITARA'),(372,'CUMBAL'),(373,'CÓRDOBA-NARIÑO'),(374,'CONTADERO'),(375,'CONSACÁ'),(376,'BUESACO'),(377,'BELÉN-NARIÑO'),(378,'BARBACOAS'),(379,'ANCUYÁ'),(380,'ALDANA'),(381,'VISTAHERMOSA'),(382,'SAN MARTÍN-NARIÑO'),(383,'SAN JUANITO'),(384,'SAN JUAN DE ARAMA'),(385,'SAN CARLOS DE GUAROA'),(386,'RESTREPO-META'),(387,'PUERTO RICO-META'),(388,'PUERTO LLERAS'),(389,'PUERTO LÓPEZ'),(390,'PUERTO GAITÁN'),(391,'PUERTO CONCORDIA-META'),(392,'LEJANÍAS'),(393,'URIBE'),(394,'LA MACARENA'),(395,'MESETAS'),(396,'MAPIRIPÁN'),(397,'GUAMAL-META'),(398,'GRANADA-META'),(399,'FUENTE DE ORO'),(400,'EL DORADO'),(401,'EL CASTILLO'),(402,'EL CALVARIO'),(403,'CUMARAL'),(404,'SAN LUIS DE CUBARRAL'),(405,'CASTILLA LA NUEVA'),(406,'CABUYARO'),(407,'BARRANCA DE UPÍA'),(408,'ACACÍAS'),(409,'VILLAVICENCIO'),(410,'TENERIFE'),(411,'SITIONUEVO'),(412,'SANTA BÁRBARA DE PINTO'),(413,'SANTA ANA'),(414,'SAN ZENÓN'),(415,'SAN SEBASTIÁN DE BUENAVISTA'),(416,'SALAMINA-MAGDALENA'),(417,'REMOLINO'),(418,'PUEBLOVIEJO'),(419,'PLATO'),(420,'PIVIJAY'),(421,'PEDRAZA'),(422,'GUAMAL-MAGDALENA'),(423,'FUNDACIÓN'),(424,'EL RETÉN'),(425,'EL PIÑÓN'),(426,'EL BANCO'),(427,'CONCORDIA-MAGDALENA'),(428,'CIÉNAGA'),(429,'CHIVOLO'),(430,'CERRO DE SAN ANTONIO'),(431,'ARACATACA'),(432,'ALGARROBO'),(433,'SANTA MARTA'),(434,'VILLANUEVA-GUAJIRA'),(435,'URUMITA'),(436,'URIBIA'),(437,'SAN JUAN DEL CESAR'),(438,'MANAURE'),(439,'MAICAO'),(440,'LA JAGUA DEL PILAR'),(441,'HATONUEVO'),(442,'FONSECA'),(443,'EL MOLINO'),(444,'DISTRACCIÓN'),(445,'DIBULLA'),(446,'BARRANCAS'),(447,'ALBANIA-LA GUAJIRA'),(448,'RIOHACHA'),(449,'YAGUARÁ'),(450,'VILLAVIEJA'),(451,'TIMANÁ'),(452,'TERUEL'),(453,'TELLO'),(454,'TESALIA'),(455,'TARQUI'),(456,'SUAZA'),(457,'SANTA MARÍA-HUILA'),(458,'SAN AGUSTÍN'),(459,'SALADOBLANCO'),(460,'RIVERA'),(461,'PITALITO'),(462,'PITAL'),(463,'PALESTINA-HUILA'),(464,'PALERMO'),(465,'PAICOL'),(466,'OPORAPA'),(467,'NÁTAGA'),(468,'LA PLATA'),(469,'LA ARGENTINA'),(470,'ÍQUIRA'),(471,'HOBO'),(472,'GUADALUPE-HUILA'),(473,'GIGANTE'),(474,'GARZÓN'),(475,'ELÍAS'),(476,'COLOMBIA'),(477,'CAMPOALEGRE'),(478,'BARAYA'),(479,'ALTAMIRA'),(480,'ALGECIRAS'),(481,'AIPE'),(482,'AGRADO'),(483,'ACEVEDO'),(484,'NEIVA'),(485,'UNGUÍA'),(486,'TADÓ'),(487,'SIPÍ'),(488,'SAN JOSÉ DEL PALMAR'),(489,'RIOSUCIO-CHOCO'),(490,'NUQUÍ'),(491,'NÓVITA'),(492,'LLORÓ'),(493,'JURADÓ'),(494,'ISTMINA'),(495,'EL CARMEN DE ATRATO'),(496,'CONDOTO'),(497,'CÉRTEGUI'),(498,'BAGADÓ'),(499,'ACANDÍ'),(500,'ZIPAQUIRÁ'),(501,'ZIPACÓN'),(502,'YACOPÍ'),(503,'VIOTÁ'),(504,'VILLETA'),(505,'VILLAPINZÓN'),(506,'VILLAGÓMEZ'),(507,'VIANÍ'),(508,'VERGARA'),(509,'ÚTICA'),(510,'UNE'),(511,'VILLA DE SAN DIEGO DE UBATÉ'),(512,'UBAQUE'),(513,'UBALÁ'),(514,'TOPAIPÍ'),(515,'TOCANCIPÁ'),(516,'TOCAIMA'),(517,'TIBIRITA'),(518,'TIBACUY'),(519,'TENJO'),(520,'TENA'),(521,'TAUSA'),(522,'TABIO'),(523,'SUTATAUSA'),(524,'SUSA'),(525,'SUPATÁ'),(526,'SUESCA'),(527,'SUBACHOQUE'),(528,'SOPÓ'),(529,'SOACHA'),(530,'SIMIJACA'),(531,'SILVANIA'),(532,'SIBATÉ'),(533,'SESQUILÉ'),(534,'SASAIMA'),(535,'SAN JUAN DE RIOSECO'),(536,'SAN FRANCISCO-CUNDINAMARCA'),(537,'SAN BERNARDO-CUNDINAMARCA'),(538,'SAN ANTONIO DEL TEQUENDAMA'),(539,'RICAURTE-CUNDINAMARCA'),(540,'APULO'),(541,'QUIPILE'),(542,'QUETAME'),(543,'QUEBRADANEGRA'),(544,'PULÍ'),(545,'PUERTO SALGAR'),(546,'PASCA'),(547,'PARATEBUENO'),(548,'PANDI'),(549,'PAIME'),(550,'PACHO'),(551,'VENECIA-CUNDINAMARCA'),(552,'NOCAIMA'),(553,'NIMAIMA'),(554,'NILO'),(555,'NEMOCÓN'),(556,'NARIÑO-CUNDINAMARCA'),(557,'MOSQUERA-CUNDINAMARCA'),(558,'MEDINA'),(559,'MANTA'),(560,'MADRID'),(561,'MACHETÁ'),(562,'LENGUAZAQUE'),(563,'LA VEGA-CUNDINAMARCA'),(564,'LA PEÑA'),(565,'LA PALMA'),(566,'LA MESA'),(567,'LA CALERA'),(568,'JUNÍN'),(569,'JERUSALÉN'),(570,'GUTIÉRREZ'),(571,'GUAYABETAL'),(572,'GUAYABAL DE SÍQUIMA'),(573,'GUATAVITA'),(574,'GUATAQUÍ'),(575,'GUASCA'),(576,'GUADUAS'),(577,'GUACHETÁ'),(578,'GRANADA-CUNDINAMARCA'),(579,'GIRARDOT'),(580,'GAMA'),(581,'GACHETÁ'),(582,'GACHANCIPÁ'),(583,'GACHALÁ'),(584,'FUSAGASUGÁ'),(585,'FÚQUENE'),(586,'FUNZA'),(587,'FOSCA'),(588,'FÓMEQUE'),(589,'FACATATIVÁ'),(590,'EL ROSAL'),(591,'EL PEÑÓN-CUNDINAMARCA'),(592,'EL COLEGIO'),(593,'CUCUNUBÁ'),(594,'COTA'),(595,'COGUA'),(596,'CHOCONTÁ'),(597,'CHOACHÍ'),(598,'CHIPAQUE'),(599,'CHÍA'),(600,'CHAGUANÍ'),(601,'CARMEN DE CARUPA'),(602,'CÁQUEZA'),(603,'CAPARRAPÍ'),(604,'CAJICÁ'),(605,'CACHIPAY'),(606,'CABRERA-CUNDINAMARCA'),(607,'BOJACÁ'),(608,'BITUIMA'),(609,'BELTRÁN'),(610,'ARBELÁEZ'),(611,'ANOLAIMA'),(612,'ANAPOIMA'),(613,'ALBÁN'),(614,'AGUA DE DIOS'),(615,'VALENCIA'),(616,'TUCHÍN'),(617,'TIERRALTA'),(618,'SAN PELAYO'),(619,'SAN JOSÉ DE URÉ'),(620,'SAN CARLOS-SANTANDER'),(621,'SAN CARLOS'),(622,'SAN BERNARDO DEL VIENTO'),(623,'SAN ANTERO'),(624,'SAN ANDRÉS DE SOTAVENTO'),(625,'SAHAGÚN'),(626,'PURÍSIMA DE LA CONCEPCIÓN'),(627,'PUERTO LIBERTADOR'),(628,'PUERTO ESCONDIDO'),(629,'PUEBLO NUEVO-CORDOBA'),(630,'PLANETA RICA'),(631,'MOÑITOS'),(632,'MONTELÍBANO'),(633,'MOMIL'),(634,'LOS CÓRDOBAS'),(635,'COTORRA'),(636,'CIÉNAGA DE ORO'),(637,'CHINÚ'),(638,'CHIMÁ-CORDODA'),(639,'CERETÉ'),(640,'BUENAVISTA-CESAR'),(641,'AYAPEL'),(642,'MONTERÍA'),(643,'TAMALAMEQUE'),(644,'SAN MARTÍN-CORDODA'),(645,'SAN DIEGO'),(646,'SAN ALBERTO'),(647,'RÍO DE ORO'),(648,'PUEBLO BELLO'),(649,'PELAYA'),(650,'PAILITAS'),(651,'MANAURE BALCÓN DEL CESAR'),(652,'LA JAGUA DE IBIRICO'),(653,'LA GLORIA'),(654,'GONZÁLEZ'),(655,'GAMARRA'),(656,'EL PASO'),(657,'EL COPEY'),(658,'CURUMANÍ'),(659,'CHIRIGUANÁ'),(660,'CHIMICHAGUA'),(661,'BOSCONIA'),(662,'BECERRIL'),(663,'ASTREA'),(664,'AGUSTÍN CODAZZI'),(665,'AGUACHICA'),(666,'VALLEDUPAR'),(667,'VILLA RICA'),(668,'TOTORÓ'),(669,'TORIBÍO'),(670,'TIMBIQUÍ'),(671,'TIMBÍO'),(672,'SUCRE-CAUCA'),(673,'SUÁREZ-CAUCA'),(674,'SILVIA'),(675,'SANTA ROSA-CAUCA'),(676,'SANTANDER DE QUILICHAO'),(677,'SAN SEBASTIÁN'),(678,'ROSAS'),(679,'PURACÉ'),(680,'PUERTO TEJADA'),(681,'PIENDAMÓ'),(682,'PIAMONTE'),(683,'PATÍA'),(684,'PADILLA'),(685,'MORALES-CAUCA'),(686,'MIRANDA'),(687,'MERCADERES'),(688,'LA VEGA-CAUCA'),(689,'LA SIERRA'),(690,'JAMBALÓ'),(691,'INZÁ'),(692,'GUAPÍ'),(693,'GUACHENÉ'),(694,'FLORENCIA-CAUCA'),(695,'EL TAMBO-CAUCA'),(696,'CORINTO'),(697,'CALOTO'),(698,'CALDONO'),(699,'CAJIBÍO'),(700,'BUENOS AIRES'),(701,'BOLÍVAR-CAUCA'),(702,'BALBOA-CAUCA'),(703,'ARGELIA-CAUCA'),(704,'ALMAGUER'),(705,'POPAYÁN'),(706,'VALPARAÍSO-CAQUETA'),(707,'SOLITA'),(708,'SOLANO'),(709,'SAN VICENTE DEL CAGUÁN'),(710,'SAN JOSÉ DEL FRAGUA'),(711,'PUERTO RICO-CAQUETA'),(712,'MORELIA'),(713,'MILÁN'),(714,'LA MONTAÑITA'),(715,'EL PAUJÍL'),(716,'EL DONCELLO'),(717,'CURILLO'),(718,'CARTAGENA DEL CHAIRÁ'),(719,'BELÉN DE LOS ANDAQUÍES'),(720,'ALBANIA-CAQUETA'),(721,'FLORENCIA'),(722,'VITERBO'),(723,'VILLAMARÍA'),(724,'VICTORIA'),(725,'SUPÍA'),(726,'SAN JOSÉ'),(727,'SAMANÁ'),(728,'SALAMINA-CALDAS'),(729,'RISARALDA'),(730,'RIOSUCIO-CALDAS'),(731,'PENSILVANIA'),(732,'PALESTINA-CALDAS'),(733,'PÁCORA'),(734,'NORCASIA'),(735,'NEIRA'),(736,'MARULANDA'),(737,'MARQUETALIA'),(738,'MARMATO'),(739,'MANZANARES'),(740,'LA MERCED'),(741,'LA DORADA'),(742,'FILADELFIA'),(743,'CHINCHINÁ'),(744,'BELALCÁZAR'),(745,'ARANZAZU'),(746,'ANSERMA'),(747,'AGUADAS'),(748,'MANIZALES'),(749,'ZETAQUIRA'),(750,'VIRACACHÁ'),(751,'VENTAQUEMADA'),(752,'ÚMBITA'),(753,'TUTAZÁ'),(754,'TUTA'),(755,'TURMEQUÉ'),(756,'TUNUNGUÁ'),(757,'TOTA'),(758,'TÓPAGA'),(759,'TOGÜÍ'),(760,'TOCA'),(761,'TIPACOQUE'),(762,'TINJACÁ'),(763,'TIBASOSA'),(764,'TIBANÁ'),(765,'TENZA'),(766,'TASCO'),(767,'SUTATENZA'),(768,'SUTAMARCHÁN'),(769,'SUSACÓN'),(770,'SORACÁ'),(771,'SOTAQUIRÁ'),(772,'SORA'),(773,'SOMONDOCO'),(774,'SOGAMOSO'),(775,'SOCHA'),(776,'SOCOTÁ'),(777,'SOATÁ'),(778,'SIACHOQUE'),(779,'SATIVASUR'),(780,'SATIVANORTE'),(781,'SANTA SOFÍA'),(782,'SANTA ROSA DE VITERBO'),(783,'SANTA MARÍA-BOYACA'),(784,'SANTANA'),(785,'SAN PABLO DE BORBUR'),(786,'SAN MIGUEL DE SEMA'),(787,'SAN MATEO'),(788,'SAN LUIS DE GACENO'),(789,'SAN JOSÉ DE PARE'),(790,'SAN EDUARDO'),(791,'SAMACÁ'),(792,'SÁCHICA'),(793,'SABOYÁ'),(794,'RONDÓN'),(795,'RÁQUIRA'),(796,'RAMIRIQUÍ'),(797,'QUÍPAMA'),(798,'PUERTO BOYACÁ'),(799,'PISBA'),(800,'PESCA'),(801,'PAZ DE RÍO'),(802,'PAYA'),(803,'PAUNA'),(804,'PANQUEBA'),(805,'PAJARITO'),(806,'PAIPA'),(807,'PÁEZ'),(808,'PACHAVITA'),(809,'OTANCHE'),(810,'OICATÁ'),(811,'NUEVO COLÓN'),(812,'NOBSA'),(813,'MUZO'),(814,'MOTAVITA'),(815,'MONIQUIRÁ'),(816,'MONGUÍ'),(817,'MONGUA'),(818,'MIRAFLORES-BOYACA'),(819,'MARIPÍ'),(820,'MACANAL'),(821,'VILLA DE LEYVA'),(822,'LA UVITA'),(823,'LA VICTORIA-BOYACA'),(824,'LA CAPILLA'),(825,'LABRANZAGRANDE'),(826,'JERICÓ-BOYACA'),(827,'JENESANO'),(828,'IZA'),(829,'GÜICÁN'),(830,'GUAYATÁ'),(831,'GUATEQUE'),(832,'GUACAMAYAS'),(833,'GARAGOA'),(834,'GÁMEZA'),(835,'GACHANTIVÁ'),(836,'FLORESTA'),(837,'FIRAVITOBA'),(838,'EL ESPINO'),(839,'EL COCUY'),(840,'DUITAMA'),(841,'CHIVOR'),(842,'CHÍQUIZA'),(843,'CUÍTIVA'),(844,'CUCAITA'),(845,'CUBARÁ'),(846,'COVARACHÍA'),(847,'CORRALES'),(848,'COPER'),(849,'CÓMBITA'),(850,'CIÉNEGA'),(851,'CHIVATÁ'),(852,'CHITARAQUE'),(853,'CHITA'),(854,'CHISCAS'),(855,'CHIQUINQUIRÁ'),(856,'CHINAVITA'),(857,'CERINZA'),(858,'CAMPOHERMOSO'),(859,'CALDAS-BOYACA'),(860,'BUSBANZÁ'),(861,'BUENAVISTA-BOYACA'),(862,'BRICEÑO-BOYACA'),(863,'BOYACÁ'),(864,'BOAVITA'),(865,'BETÉITIVA'),(866,'BERBEO'),(867,'BELÉN-BOYACA'),(868,'ARCABUCO'),(869,'AQUITANIA'),(870,'ALMEIDA'),(871,'TUNJA'),(872,'ZAMBRANO'),(873,'VILLANUEVA-BOYACA'),(874,'TURBANÁ'),(875,'TURBACO'),(876,'TALAIGUA NUEVO'),(877,'SOPLAVIENTO'),(878,'SIMITÍ'),(879,'SANTA ROSA DEL SUR'),(880,'SANTA CATALINA'),(881,'SAN PABLO-BOLIVAR'),(882,'SAN MARTÍN DE LOBA'),(883,'SAN JUAN NEPOMUCENO'),(884,'SAN JACINTO DEL CAUCA'),(885,'SAN JACINTO'),(886,'SAN FERNANDO'),(887,'SAN CRISTÓBAL'),(888,'RÍO VIEJO'),(889,'REGIDOR'),(890,'PINILLOS'),(891,'NOROSÍ'),(892,'MORALES-BOLIVAR'),(893,'MOMPÓS'),(894,'MONTECRISTO'),(895,'MARÍA LA BAJA'),(896,'MARGARITA'),(897,'MAHATES'),(898,'MAGANGUÉ'),(899,'HATILLO DE LOBA'),(900,'EL PEÑÓN-BOLIVAR'),(901,'EL GUAMO'),(902,'EL CARMEN DE BOLÍVAR'),(903,'CLEMENCIA'),(904,'CÓRDOBA-BOLIVAR'),(905,'CICUCO'),(906,'CANTAGALLO'),(907,'CALAMAR-BOLIVAR'),(908,'BARRANCO DE LOBA'),(909,'ARROYOHONDO'),(910,'ARJONA'),(911,'ARENAL'),(912,'ALTOS DEl ROSARIO'),(913,'ACHÍ'),(914,'CARTAGENA DE INDIAS'),(915,'BOGOTÁ, D.C.'),(916,'USIACURÍ'),(917,'TUBARÁ'),(918,'SUAN'),(919,'SOLEDAD'),(920,'SANTO TOMÁS'),(921,'SANTA LUCÍA'),(922,'SABANALARGA-ATLÁNTICO'),(923,'SABANAGRANDE'),(924,'REPELÓN'),(925,'PUERTO COLOMBIA-ATLÁNTICO'),(926,'PONEDERA'),(927,'POLONUEVO'),(928,'PIOJÓ'),(929,'PALMAR DE VARELA'),(930,'LURUACO'),(931,'JUAN DE ACOSTA'),(932,'GALAPA'),(933,'CANDELARIA-ATLÁNTICO'),(934,'CAMPO DE LA CRUZ'),(935,'BARANOA'),(936,'BARRANQUILLA'),(937,'ZARAGOZA'),(938,'YOLOMBÓ'),(939,'YARUMAL'),(940,'YALÍ'),(941,'VIGIA DEL FUERTE'),(942,'VENECIA-ANTIOQUIA'),(943,'VEGACHÍ'),(944,'VALPARAÍSO-ANTIOQUIA'),(945,'VALDIVIA'),(946,'URRAO'),(947,'URAMITA'),(948,'TURBO'),(949,'TOLEDO-ANTIOQUIA'),(950,'TITIRIBÍ'),(951,'TARSO'),(952,'TARAZÁ'),(953,'TÁMESIS'),(954,'SOPETRÁN'),(955,'SONSÓN'),(956,'SEGOVIA'),(957,'EL SANTUARIO'),(958,'SANTO DOMINGO'),(959,'SANTA ROSA DE OSOS'),(960,'SANTA BÁRBARA-ANTIOQUIA'),(961,'SAN ROQUE'),(962,'SAN RAFAEL'),(963,'SAN PEDRO DE URABÁ'),(964,'SAN PEDRO DE LOS MILAGROS'),(965,'SAN LUIS-ANTIOQUIA'),(966,'SAN JUAN DE URABÁ'),(967,'SAN JOSÉ DE LA MONTAÑA'),(968,'SAN JERÓNIMO'),(969,'SAN FRANCISCO-ANTIOQUIA'),(970,'SAN CARLOS-ANTIOQUIA'),(971,'SAN ANDRÉS DE CUERQUÍA'),(972,'SALGAR'),(973,'SABANETA'),(974,'SABANALARGA'),(975,'RIONEGRO-ANTIOQUIA'),(976,'RETIRO'),(977,'REMEDIOS'),(978,'PUERTO TRIUNFO'),(979,'PUERTO NARE'),(980,'PUERTO BERRÍO'),(981,'PUEBLORRICO'),(982,'PEQUE'),(983,'EL PEÑOL-ANTIOQUIA'),(984,'OLAYA'),(985,'NECHÍ'),(986,'NECOCLÍ'),(987,'NARIÑO-ANTIOQUIA'),(988,'MANATÍ'),(989,'MUTATÁ'),(990,'MURINDÓ'),(991,'MONTEBELLO'),(992,'MARINILLA'),(993,'MACEO'),(994,'LIBORINA'),(995,'LA UNIÓN-ANTIOQUIA'),(996,'LA PINTADA'),(997,'LA ESTRELLA'),(998,'LA CEJA'),(999,'JERICÓ-ANTIOQUIA'),(1000,'JARDÍN'),(1001,'ITUANGO'),(1002,'ITAGÜÍ'),(1003,'HISPANIA'),(1004,'HELICONIA'),(1005,'GUATAPÉ'),(1006,'GUARNE'),(1007,'GUADALUPE-ANTIOQUIA'),(1008,'GRANADA-ANTIOQUIA'),(1009,'GÓMEZ PLATA'),(1010,'GIRARDOTA'),(1011,'GIRALDO'),(1012,'FRONTINO'),(1013,'FREDONIA'),(1014,'ENVIGADO'),(1015,'ENTRERRÍOS'),(1016,'EL BAGRE'),(1017,'EBÉJICO'),(1018,'DON MATÍAS'),(1019,'DABEIBA'),(1020,'COPACABANA'),(1021,'CONCORDIA-ANTIOQUIA'),(1022,'CONCEPCIÓN-ANTIOQUIA'),(1023,'COCORNÁ'),(1024,'CISNEROS'),(1025,'CHIGORODÓ'),(1026,'CAUCASIA'),(1027,'CAROLINA'),(1028,'EL CARMEN DE VIBORAL'),(1029,'CAREPA'),(1030,'CARAMANTA'),(1031,'CARACOLÍ'),(1032,'CAÑASGORDAS'),(1033,'MALAMBO'),(1034,'CAMPAMENTO'),(1035,'CALDAS-ANTIOQUIA'),(1036,'CAICEDO'),(1037,'CÁCERES'),(1038,'BURITICÁ'),(1039,'BRICEÑO-ANTIOQUIA'),(1040,'CIUDAD BOLÍVAR'),(1041,'BETULIA-ANTIOQUIA'),(1042,'BETANIA'),(1043,'BELLO'),(1044,'BELMIRA'),(1045,'BARBOSA-ANTIOQUIA'),(1046,'ARMENIA-ANTIOQUIA'),(1047,'ARGELIA-ANTIOQUIA'),(1048,'ARBOLETES'),(1049,'APARTADÓ'),(1050,'ANZÁ'),(1051,'SANTA FÉ DE ANTIOQUIA'),(1052,'ANORÍ'),(1053,'ANGOSTURA'),(1054,'ANGELÓPOLIS'),(1055,'ANDES'),(1056,'AMALFI'),(1057,'AMAGÁ'),(1058,'ALEJANDRÍA'),(1059,'ABRIAQUÍ'),(1060,'ABEJORRAL'),(1061,'MEDELLÍN'),(1062,'NINGUNO'),(1063,'DEFAULT');
/*!40000 ALTER TABLE `Ciudad` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Departamento` (
  `idDepartamento` INT(30) NOT NULL AUTO_INCREMENT,
  `nombreDepartamento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  UNIQUE INDEX `idDepartamento_UNIQUE` (`idDepartamento` ASC),
  UNIQUE INDEX `nombreDepartamento_UNIQUE` (`nombreDepartamento` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `Departamento`
--

LOCK TABLES `Departamento` WRITE;
/*!40000 ALTER TABLE `Departamento` DISABLE KEYS */;
INSERT INTO `Departamento` VALUES (1,'VICHADA'),(2,'VAUPES'),(3,'VALLE DEL CAUCA'),(4,'TOLIMA'),(5,'SUCRE'),(6,'NORTE DE SANTANDER'),(7,'RISARALDA'),(8,'QUINDIO'),(9,'PUTUMAYO'),(10,'SANTANDER'),(11,'NARIÑO'),(12,'META'),(13,'MAGDALENA'),(14,'LA GUAJIRA'),(15,'HUILA'),(16,'GUAVIARE'),(17,'GUAINIA'),(18,'CUNDINAMARCA'),(19,'CÓRDOBA'),(20,'CHOCÓ'),(21,'CESAR'),(22,'CAUCA'),(23,'CASANARE'),(24,'CAQUETA'),(25,'CALDAS'),(26,'BOYACA'),(27,'BOLIVAR'),(28,'BOGOTA D.C'),(29,'ATLÁNTICO'),(30,'SAN ANDRÉS & PROVIDENCIA'),(31,'ARAUCA'),(32,'AMAZONAS'),(33,'ANTIOQUIA'),(34,'NINGUNO'),(35,'DEFAULT');
/*!40000 ALTER TABLE `Departamento` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Empleado` (
  `idEmpleado` INT(30) NOT NULL AUTO_INCREMENT,
  `identificacionEmpleado` INT(30) NOT NULL,
  `nombresEmpleado` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `apellidosEmpleado` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `idDepartamento` INT(30) NOT NULL,
  `idCiudad` INT(30) NOT NULL,
  `direccionEmpleado` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `telefonoEmpleado` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `correoEmpleado` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  UNIQUE INDEX `idEmpleado_UNIQUE` (`idEmpleado` ASC),
  UNIQUE INDEX `identificacionEmpleado_UNIQUE` (`identificacionEmpleado` ASC),
  INDEX `idDepartamentoEmpleado` (`idDepartamento` ASC),
  INDEX `idCiudadEmpleado` (`idCiudad` ASC),
  CONSTRAINT `idCiudadEmpleado`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `moto10racingHBT`.`Ciudad` (`idCiudad`)
    ON UPDATE CASCADE,
  CONSTRAINT `idDepartamentoEmpleado`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `moto10racingHBT`.`Departamento` (`idDepartamento`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;

--
-- Dumping data for table `Empleado`
--

LOCK TABLES `Empleado` WRITE;
/*!40000 ALTER TABLE `Empleado` DISABLE KEYS */;
INSERT INTO `Empleado` VALUES (1,'1','DEFAULT','DEFAULT',1,1,'DEFAULT','DEFAULT','DEFAULT@');
/*!40000 ALTER TABLE `Empleado` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`TipoDocumento` (
  `idTipoDocumento` INT(30) NOT NULL AUTO_INCREMENT,
  `descripcionDocumento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipoDocumento`),
  UNIQUE INDEX `idTipoDocumento_UNIQUE` (`idTipoDocumento` ASC))
ENGINE = InnoDB;

--
-- Dumping data for table `TipoDocumento`
--

LOCK TABLES `TipoDocumento` WRITE;
/*!40000 ALTER TABLE `TipoDocumento` DISABLE KEYS */;
INSERT INTO `TipoDocumento` VALUES (1,'C.C'),(2,'NIT'),(3,'C.E');
/*!40000 ALTER TABLE `TipoDocumento` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`TipoPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`TipoPersona` (
  `idTipoPersona` INT(30) NOT NULL AUTO_INCREMENT,
  `descripcionPersona` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipoPersona`),
  UNIQUE INDEX `idTipoPersona_UNIQUE` (`idTipoPersona` ASC))
ENGINE = InnoDB;

--
-- Dumping data for table `TipoPersona`
--

LOCK TABLES `TipoPersona` WRITE;
/*!40000 ALTER TABLE `TipoPersona` DISABLE KEYS */;
INSERT INTO `TipoPersona` VALUES (1,'ACREEDOR'),(2,'PROVEEDOR');
/*!40000 ALTER TABLE `TipoPersona` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Persona` (
  `idPersona` INT(30) NOT NULL AUTO_INCREMENT,
  `idTipoPersona` INT(30) NOT NULL,
  `idTipoDocumento` INT(30) NOT NULL,
  `identificacionPersona` INT(30) NOT NULL,
  `nombresPersona` VARCHAR(100) NOT NULL,
  `apellidosPersona` VARCHAR(100) NOT NULL,
  `idDepartamento` INT(30) NOT NULL,
  `idCiudad` INT(30) NOT NULL,
  `direccionPersona` VARCHAR(100) NULL,
  `telefonoPersona` VARCHAR(100) NULL,
  `correoPersona` VARCHAR(100) NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idPersona` ASC),
  UNIQUE INDEX `identificacionPersona_UNIQUE` (`identificacionPersona` ASC),
  INDEX `idDepartamentoPersona` (`idDepartamento` ASC),
  INDEX `idCiudadPersona` (`idCiudad` ASC),
  INDEX `idTipoDocumentoPersona` (`idTipoDocumento` ASC),
  INDEX `idTipoPersonaPersona` (`idTipoPersona` ASC),
  CONSTRAINT `idCiudadPersona`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `moto10racingHBT`.`Ciudad` (`idCiudad`)
    ON UPDATE CASCADE,
  CONSTRAINT `idDepartamentoPersona`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `moto10racingHBT`.`Departamento` (`idDepartamento`)
    ON UPDATE CASCADE,
  CONSTRAINT `idTipoDocumentoPersona`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `moto10racingHBT`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idTipoPersonaPersona`
    FOREIGN KEY (`idTipoPersona`)
    REFERENCES `moto10racingHBT`.`TipoPersona` (`idTipoPersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `Persona`
--

LOCK TABLES `Persona` WRITE;
/*!40000 ALTER TABLE `Persona` DISABLE KEYS */;
INSERT INTO `Persona` VALUES (1,1,1,'1','DEFAULT','DEFAULT',1,1,'DEFAULT','DEFAULT','DEFAULT@');
/*!40000 ALTER TABLE `Persona` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`TipoTransaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`TipoTransaccion` (
  `idTipoTransaccion` INT(30) NOT NULL AUTO_INCREMENT,
  `descripcionTransaccion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idTipoTransaccion`),
  UNIQUE INDEX `idTipoTransaccion_UNIQUE` (`idTipoTransaccion` ASC))
ENGINE = InnoDB;


--
-- Dumping data for table `TipoTransaccion`
--

LOCK TABLES `TipoTransaccion` WRITE;
/*!40000 ALTER TABLE `TipoTransaccion` DISABLE KEYS */;
INSERT INTO `TipoTransaccion` VALUES (1,'CONTADO'),(2,'CREDITO');
/*!40000 ALTER TABLE `TipoTransaccion` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Compra` (
  `idCompra` INT(30) NOT NULL AUTO_INCREMENT,
  `numeroCompra` VARCHAR(30) NOT NULL,
  `idEmpleado` INT(30) NOT NULL,
  `idPersona` INT(30) NOT NULL,
  `totalCompra` FLOAT NOT NULL,
  `idTipoTransaccion` INT(30) NOT NULL,
  `fechaCompra` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`idCompra`),
  UNIQUE INDEX `idCompra_UNIQUE` (`idCompra` ASC),
  INDEX `idEmpleadoCompra_idx` (`idEmpleado` ASC),
  INDEX `idPersonaCompra_idx` (`idPersona` ASC),
  INDEX `idTipoTransaccionCompra_idx` (`idTipoTransaccion` ASC),
  CONSTRAINT `idEmpleadoCompra`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `moto10racingHBT`.`Empleado` (`idEmpleado`)
    ON UPDATE CASCADE,
  CONSTRAINT `idPersonaCompra`
    FOREIGN KEY (`idPersona`)
    REFERENCES `moto10racingHBT`.`Persona` (`idPersona`)
    ON UPDATE CASCADE,
  CONSTRAINT `idTipoTransaccionCompra`
    FOREIGN KEY (`idTipoTransaccion`)
    REFERENCES `moto10racingHBT`.`TipoTransaccion` (`idTipoTransaccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Modulos` (
  `idModulos` INT(11) NOT NULL AUTO_INCREMENT,
  `codigoModulo` VARCHAR(50) NOT NULL,
  `nombreModulo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idModulos`),
  UNIQUE INDEX `idModulos_UNIQUE` (`idModulos` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Menu` (
  `idMenu` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreMenu` VARCHAR(50) NOT NULL,
  `linkMenu` VARCHAR(50) NOT NULL,
  `idModulos` INT(11) NOT NULL,
  PRIMARY KEY (`idMenu`),
  UNIQUE INDEX `idMenu_UNIQUE` (`idMenu` ASC),
  INDEX `fk_Menu_Modulos1_idx` (`idModulos` ASC),
  CONSTRAINT `fk_Menu_Modulos1`
    FOREIGN KEY (`idModulos`)
    REFERENCES `moto10racingHBT`.`Modulos` (`idModulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Perfiles` (
  `idPerfiles` INT(11) NOT NULL AUTO_INCREMENT,
  `codigoPerfil` VARCHAR(50) NOT NULL,
  `nombrePefil` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPerfiles`),
  UNIQUE INDEX `idPerfiles_UNIQUE` (`idPerfiles` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`PresentacionProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`PresentacionProducto` (
  `idPresentacionProducto` INT(30) NOT NULL AUTO_INCREMENT,
  `descripcionPresentacionPro` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  PRIMARY KEY (`idPresentacionProducto`),
  UNIQUE INDEX `idPresentacionProducto_UNIQUE` (`idPresentacionProducto` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;

--
-- Dumping data for table `PresentacionProducto`
--

LOCK TABLES `PresentacionProducto` WRITE;
/*!40000 ALTER TABLE `PresentacionProducto` DISABLE KEYS */;
INSERT INTO `PresentacionProducto` VALUES (1,'DEFAULT'),(2,'CAJA'),(3,'SACHET'),(4,'BOLSA'),(5,'SIN EMPAQUE');
/*!40000 ALTER TABLE `PresentacionProducto` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`UbicacionProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`UbicacionProducto` (
  `idUbicacionProducto` INT(30) NOT NULL AUTO_INCREMENT,
  `descripcionUbicacionPro` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUbicacionProducto`),
  UNIQUE INDEX `idUbicacionProducto_UNIQUE` (`idUbicacionProducto` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 261
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `UbicacionProducto`
--

LOCK TABLES `UbicacionProducto` WRITE;
/*!40000 ALTER TABLE `UbicacionProducto` DISABLE KEYS */;
INSERT INTO `UbicacionProducto` VALUES (1,'A1'),(2,'A2'),(3,'A3'),(4,'A4'),(5,'A5'),(6,'A6'),(7,'A7'),(8,'A8'),(9,'A9'),(10,'A10'),(11,'B1'),(12,'B2'),(13,'B3'),(14,'B4'),(15,'B5'),(16,'B6'),(17,'B7'),(18,'B8'),(19,'B9'),(20,'B10'),(21,'C1'),(22,'C2'),(23,'C3'),(24,'C4'),(25,'C5'),(26,'C6'),(27,'C7'),(28,'C8'),(29,'C9'),(30,'C10'),(31,'D1'),(32,'D2'),(33,'D3'),(34,'D4'),(35,'D5'),(36,'D6'),(37,'D7'),(38,'D8'),(39,'D9'),(40,'D10'),(41,'E1'),(42,'E2'),(43,'E3'),(44,'E4'),(45,'E5'),(46,'E6'),(47,'E7'),(48,'E8'),(49,'E9'),(50,'E10'),(51,'F1'),(52,'F2'),(53,'F3'),(54,'F4'),(55,'F5'),(56,'F6'),(57,'F7'),(58,'F8'),(59,'F9'),(60,'F10'),(61,'G1'),(62,'G2'),(63,'G3'),(64,'G4'),(65,'G5'),(66,'G6'),(67,'G7'),(68,'G8'),(69,'G9'),(70,'G10'),(71,'H1'),(72,'H2'),(73,'H3'),(74,'H4'),(75,'H5'),(76,'H6'),(77,'H7'),(78,'H8'),(79,'H9'),(80,'H10'),(81,'I1'),(82,'I2'),(83,'I3'),(84,'I4'),(85,'I5'),(86,'I6'),(87,'I7'),(88,'I8'),(89,'I9'),(90,'I10'),(91,'J1'),(92,'J2'),(93,'J3'),(94,'J4'),(95,'J5'),(96,'J6'),(97,'J7'),(98,'J8'),(99,'J9'),(100,'J10'),(101,'K1'),(102,'K2'),(103,'K3'),(104,'K4'),(105,'K5'),(106,'K6'),(107,'K7'),(108,'K8'),(109,'K9'),(110,'K10'),(111,'L1'),(112,'L2'),(113,'L3'),(114,'L4'),(115,'L5'),(116,'L6'),(117,'L7'),(118,'L8'),(119,'L9'),(120,'L10'),(121,'M1'),(122,'M2'),(123,'M3'),(124,'M4'),(125,'M5'),(126,'M6'),(127,'M7'),(128,'M8'),(129,'M9'),(130,'M10'),(131,'N1'),(132,'N2'),(133,'N3'),(134,'N4'),(135,'N5'),(136,'N6'),(137,'N7'),(138,'N8'),(139,'N9'),(140,'N10'),(141,'O1'),(142,'O2'),(143,'O3'),(144,'O4'),(145,'O5'),(146,'O6'),(147,'O7'),(148,'O8'),(149,'O9'),(150,'O10'),(151,'P1'),(152,'P2'),(153,'P3'),(154,'P4'),(155,'P5'),(156,'P6'),(157,'P7'),(158,'P8'),(159,'P9'),(160,'P10'),(161,'Q1'),(162,'Q2'),(163,'Q3'),(164,'Q4'),(165,'Q5'),(166,'Q6'),(167,'Q7'),(168,'Q8'),(169,'Q9'),(170,'Q10'),(171,'R1'),(172,'R2'),(173,'R3'),(174,'R4'),(175,'R5'),(176,'R6'),(177,'R7'),(178,'R8'),(179,'R9'),(180,'R10'),(181,'S1'),(182,'S2'),(183,'S3'),(184,'S4'),(185,'S5'),(186,'S6'),(187,'S7'),(188,'S8'),(189,'S9'),(190,'S10'),(191,'T1'),(192,'T2'),(193,'T3'),(194,'T4'),(195,'T5'),(196,'T6'),(197,'T7'),(198,'T8'),(199,'T9'),(200,'T10'),(201,'U1'),(202,'U2'),(203,'U3'),(204,'U4'),(205,'U5'),(206,'U6'),(207,'U7'),(208,'U8'),(209,'U9'),(210,'U10'),(211,'V1'),(212,'V2'),(213,'V3'),(214,'V4'),(215,'V5'),(216,'V6'),(217,'V7'),(218,'V8'),(219,'V9'),(220,'V10'),(221,'W1'),(222,'W2'),(223,'W3'),(224,'W4'),(225,'W5'),(226,'W6'),(227,'W7'),(228,'W8'),(229,'W9'),(230,'W10'),(231,'X1'),(232,'X2'),(233,'X3'),(234,'X4'),(235,'X5'),(236,'X6'),(237,'X7'),(238,'X8'),(239,'X9'),(240,'X10'),(241,'Y1'),(242,'Y2'),(243,'Y3'),(244,'Y4'),(245,'Y5'),(246,'Y6'),(247,'Y7'),(248,'Y8'),(249,'Y9'),(250,'Y10'),(251,'Z1'),(252,'Z2'),(253,'Z3'),(254,'Z4'),(255,'Z5'),(256,'Z6'),(257,'Z7'),(258,'Z8'),(259,'Z9'),(260,'Z10');
/*!40000 ALTER TABLE `UbicacionProducto` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Producto` (
  `idProducto` INT(30) NOT NULL AUTO_INCREMENT,
  `codigoProducto` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `nombreProducto` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `descripcionProducto` TEXT CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `stockProducto` INT NOT NULL,
  `valorCompraProducto` FLOAT NOT NULL,
  `valorVentaProducto` FLOAT NOT NULL,
  `stockMinimo` INT NOT NULL,
  `IVA` ENUM('SI', 'NO') NOT NULL,
  `idCategoria` INT(30) NOT NULL,
  `idPresentacionProducto` INT(30) NOT NULL,
  `idUbicacionProducto` INT(30) NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC),
  INDEX `idCategoriaProducto_idx` (`idCategoria` ASC),
  UNIQUE INDEX `codigoProducto_UNIQUE` (`codigoProducto` ASC),
  INDEX `idPresentacionProductoProducto_idx` (`idPresentacionProducto` ASC),
  INDEX `idUbicacionProductoProducto_idx` (`idUbicacionProducto` ASC),
  CONSTRAINT `idCategoriaProducto`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `moto10racingHBT`.`Categoria` (`idCategoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idPresentacionProductoProducto`
    FOREIGN KEY (`idPresentacionProducto`)
    REFERENCES `moto10racingHBT`.`PresentacionProducto` (`idPresentacionProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idUbicacionProductoProducto`
    FOREIGN KEY (`idUbicacionProducto`)
    REFERENCES `moto10racingHBT`.`UbicacionProducto` (`idUbicacionProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;

--
-- Dumping data for table `Producto`
--

LOCK TABLES `Producto` WRITE;
/*!40000 ALTER TABLE `Producto` DISABLE KEYS */;
INSERT INTO `Producto` VALUES (1,'1DEFAULT%','DEFAULT','DEFAULT',100,15000,30000,5,'SI',1,1,1);
/*!40000 ALTER TABLE `Producto` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Roles` (
  `idRoles` INT(11) NOT NULL AUTO_INCREMENT,
  `codigoRol` VARCHAR(50) NOT NULL,
  `nombreRol` VARCHAR(50) NOT NULL,
  `idModulos` INT(11) NOT NULL,
  PRIMARY KEY (`idRoles`),
  UNIQUE INDEX `idRoles_UNIQUE` (`idRoles` ASC),
  INDEX `fk_Roles_Modulos1_idx` (`idModulos` ASC),
  CONSTRAINT `fk_Roles_Modulos1`
    FOREIGN KEY (`idModulos`)
    REFERENCES `moto10racingHBT`.`Modulos` (`idModulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Venta` (
  `idVenta` INT(30) NOT NULL AUTO_INCREMENT,
  `numeroVenta` VARCHAR(30) NOT NULL,
  `idEmpleado` INT(30) NOT NULL,
  `idPersona` INT(30) NOT NULL,
  `totalVenta` FLOAT NOT NULL,
  `totalDescuentoVenta` FLOAT NULL,
  `idTipoTransaccion` INT(30) NOT NULL,
  `fechaVenta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`idVenta`),
  UNIQUE INDEX `idVenta_UNIQUE` (`idVenta` ASC),
  INDEX `idEmpleadoVenta_idx` (`idEmpleado` ASC),
  INDEX `idPersonaVenta_idx` (`idPersona` ASC),
  INDEX `idTipoTransaccionVenta_idx` (`idTipoTransaccion` ASC),
  CONSTRAINT `idEmpleadoVenta`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `moto10racingHBT`.`Empleado` (`idEmpleado`)
    ON UPDATE CASCADE,
  CONSTRAINT `idPersonaVenta`
    FOREIGN KEY (`idPersona`)
    REFERENCES `moto10racingHBT`.`Persona` (`idPersona`)
    ON UPDATE CASCADE,
  CONSTRAINT `idTipoTransaccionVenta`
    FOREIGN KEY (`idTipoTransaccion`)
    REFERENCES `moto10racingHBT`.`TipoTransaccion` (`idTipoTransaccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`creditoCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`creditoCompra` (
  `idCreditoCompra` INT(30) NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT(30) NOT NULL,
  `idPersona` INT(30) NOT NULL,
  `creditoNuevo` FLOAT NOT NULL,
  `fechaAbono` DATE NOT NULL,
  PRIMARY KEY (`idCreditoCompra`),
  UNIQUE INDEX `idEmpleado_UNIQUE` (`idEmpleado` ASC),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  INDEX `idCreditoCompra_UNIQUE` (`idCreditoCompra` ASC),
  CONSTRAINT `idEmpleadoCreditoCompra`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `moto10racingHBT`.`Empleado` (`idEmpleado`)
    ON UPDATE CASCADE,
  CONSTRAINT `idPersonaCreditoCompra`
    FOREIGN KEY (`idPersona`)
    REFERENCES `moto10racingHBT`.`Persona` (`idPersona`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`creditoVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`creditoVenta` (
  `idCreditoVenta` INT(30) NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT(30) NOT NULL,
  `idPersona` INT(30) NOT NULL,
  `creditoNuevo` FLOAT NOT NULL,
  `fechaAbono` DATE NOT NULL,
  PRIMARY KEY (`idCreditoVenta`),
  UNIQUE INDEX `idCreditoVenta_UNIQUE` (`idCreditoVenta` ASC),
  INDEX `idEmpleadoCreditoVenta_idx` (`idEmpleado` ASC),
  INDEX `idPersonaCreditoVenta_idx` (`idPersona` ASC),
  CONSTRAINT `idEmpleadoCreditoVenta`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `moto10racingHBT`.`Empleado` (`idEmpleado`)
    ON UPDATE CASCADE,
  CONSTRAINT `idPersonaCreditoVenta`
    FOREIGN KEY (`idPersona`)
    REFERENCES `moto10racingHBT`.`Persona` (`idPersona`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`detalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`detalleCompra` (
  `idDetalleCompra` INT(30) NOT NULL AUTO_INCREMENT,
  `idCompra` INT(30) NOT NULL,
  `idProducto` INT(30) NOT NULL,
  `codigoProducto` VARCHAR(100) NOT NULL,
  `nombreProducto` VARCHAR(100) NOT NULL,
  `valorCompraProducto` FLOAT NOT NULL,
  `valorVentaProducto` FLOAT NOT NULL,
  `unidadesCompradas` INT(30) NOT NULL,
  `totalDetalleCompra` FLOAT NOT NULL,
  PRIMARY KEY (`idDetalleCompra`),
  UNIQUE INDEX `idDetalleCompra_UNIQUE` (`idDetalleCompra` ASC),
  INDEX `idDetalleCompraPdcto_idx` (`idProducto` ASC),
  INDEX `idDetalleCompraCompra_idx` (`idCompra` ASC),
  CONSTRAINT `idDetalleCompraCompra`
    FOREIGN KEY (`idCompra`)
    REFERENCES `moto10racingHBT`.`Compra` (`idCompra`)
    ON UPDATE CASCADE,
  CONSTRAINT `idDetalleCompraPdcto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `moto10racingHBT`.`Producto` (`idProducto`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`detalleCreditoCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`detalleCreditoCompra` (
  `idDetalleCreditoCompra` INT(30) NOT NULL AUTO_INCREMENT,
  `idCreditoCompra` INT(30) NOT NULL,
  `idCompra` INT(30) NOT NULL,
  `creditoCompraActual` FLOAT NOT NULL,
  `abonoCreditoCompra` FLOAT NOT NULL,
  PRIMARY KEY (`idDetalleCreditoCompra`),
  UNIQUE INDEX `idDetalleCreditoCompra_UNIQUE` (`idDetalleCreditoCompra` ASC),
  UNIQUE INDEX `idCreditoCompra_UNIQUE` (`idCreditoCompra` ASC),
  UNIQUE INDEX `idCompra_UNIQUE` (`idCompra` ASC),
  CONSTRAINT `idCompraDetalleCreditoCompra`
    FOREIGN KEY (`idCompra`)
    REFERENCES `moto10racingHBT`.`Compra` (`idCompra`)
    ON UPDATE CASCADE,
  CONSTRAINT `idCreditoCompraDetalleCreditoCompra`
    FOREIGN KEY (`idCreditoCompra`)
    REFERENCES `moto10racingHBT`.`creditoCompra` (`idCreditoCompra`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`detalleCreditoVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`detalleCreditoVenta` (
  `idDetalleCreditoVenta` INT(30) NOT NULL AUTO_INCREMENT,
  `idCreditoVenta` INT(30) NOT NULL,
  `idVenta` INT(30) NOT NULL,
  `creditoVentaActual` FLOAT NOT NULL,
  `abonoCreditoVenta` FLOAT NOT NULL,
  PRIMARY KEY (`idDetalleCreditoVenta`),
  UNIQUE INDEX `idDetalleCreditoVenta_UNIQUE` (`idDetalleCreditoVenta` ASC),
  UNIQUE INDEX `idVenta_UNIQUE` (`idVenta` ASC),
  UNIQUE INDEX `idCreditoVenta_UNIQUE` (`idCreditoVenta` ASC),
  CONSTRAINT `idCreditoVentaDetalleCreditoVenta`
    FOREIGN KEY (`idCreditoVenta`)
    REFERENCES `moto10racingHBT`.`creditoVenta` (`idCreditoVenta`)
    ON UPDATE CASCADE,
  CONSTRAINT `idVentaDetalleCreditoVenta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `moto10racingHBT`.`Venta` (`idVenta`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`detalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`detalleVenta` (
  `idDetalleVenta` INT(30) NOT NULL AUTO_INCREMENT,
  `idVenta` INT(30) NOT NULL,
  `idProducto` INT(30) NOT NULL,
  `codigoProducto` VARCHAR(100) NOT NULL,
  `nombreProducto` VARCHAR(100) NOT NULL,
  `valorVentaProducto` FLOAT NOT NULL,
  `IVA` VARCHAR(30) NOT NULL,
  `unidadesVendidas` INT(30) NOT NULL,
  `totalDetalleVenta` FLOAT NOT NULL,
  PRIMARY KEY (`idDetalleVenta`),
  UNIQUE INDEX `idDetalleVenta_UNIQUE` (`idDetalleVenta` ASC),
  INDEX `idDetalleVentaPdcto_idx` (`idProducto` ASC),
  INDEX `idDetalleVentaVenta_idx` (`idVenta` ASC),
  CONSTRAINT `idDetalleVentaPdcto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `moto10racingHBT`.`Producto` (`idProducto`)
    ON UPDATE CASCADE,
  CONSTRAINT `idDetalleVentaVenta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `moto10racingHBT`.`Venta` (`idVenta`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`empleado_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`empleado_Roles` (
  `idEmpleado_Roles` INT(11) NOT NULL AUTO_INCREMENT,
  `idEmpelado` INT(11) NOT NULL,
  `idRoles` INT(11) NOT NULL,
  PRIMARY KEY (`idEmpleado_Roles`),
  UNIQUE INDEX `idempleado_roles_UNIQUE` (`idEmpleado_Roles` ASC),
  INDEX `id_empelado_idx` (`idEmpelado` ASC),
  INDEX `idroles_idx` (`idRoles` ASC),
  CONSTRAINT `id_empelado`
    FOREIGN KEY (`idEmpelado`)
    REFERENCES `moto10racingHBT`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idroles`
    FOREIGN KEY (`idRoles`)
    REFERENCES `moto10racingHBT`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`empleado_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`empleado_Usuarios` (
  `idEmpleado_Usuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT(11) NOT NULL,
  `idPerfiles` INT(11) NOT NULL,
  PRIMARY KEY (`idEmpleado_Usuarios`),
  UNIQUE INDEX `idempleado_usuarios_UNIQUE` (`idEmpleado_Usuarios` ASC),
  INDEX `id_empleado_idx` (`idEmpleado` ASC),
  INDEX `idperfiles_idx` (`idPerfiles` ASC),
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `moto10racingHBT`.`Empleado` (`idEmpleado`)
    ON UPDATE CASCADE,
  CONSTRAINT `idPerfiles`
    FOREIGN KEY (`idPerfiles`)
    REFERENCES `moto10racingHBT`.`Perfiles` (`idPerfiles`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`per_Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`per_Modulos` (
  `idPer_Modulos` INT(11) NOT NULL AUTO_INCREMENT,
  `Perfiles_idPerfiles` INT(11) NOT NULL,
  `Modulos_idModulos` INT(11) NOT NULL,
  PRIMARY KEY (`idPer_Modulos`),
  UNIQUE INDEX `idper_modulos_UNIQUE` (`idPer_Modulos` ASC),
  INDEX `fk_per_modulos_Perfiles1_idx` (`Perfiles_idPerfiles` ASC),
  INDEX `fk_per_modulos_Modulos1_idx` (`Modulos_idModulos` ASC),
  CONSTRAINT `fk_per_modulos_Modulos1`
    FOREIGN KEY (`Modulos_idModulos`)
    REFERENCES `moto10racingHBT`.`Modulos` (`idModulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_per_modulos_Perfiles1`
    FOREIGN KEY (`Perfiles_idPerfiles`)
    REFERENCES `moto10racingHBT`.`Perfiles` (`idPerfiles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moto10racingHBT`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moto10racingHBT`.`Usuario` (
  `idUsuario` INT(30) NOT NULL AUTO_INCREMENT,
  `userEmp` VARCHAR(30) NOT NULL,
  `passEmp` VARCHAR(333) NOT NULL,
  `idEmpleado` INT(30) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `idEmpleadoUsuario_idx` (`idEmpleado` ASC),
  CONSTRAINT `idEmpleadoUsuario`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `moto10racingHBT`.`Empleado` (`idEmpleado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

--
-- Dumping data for table `Usuario`
--

LOCK TABLES `Usuario` WRITE;
/*!40000 ALTER TABLE `Usuario` DISABLE KEYS */;
INSERT INTO `Usuario` VALUES (1,'DEFAULT','1625cdb75d25d9f699fd2779f44095b6e320767f606f095eb7edab5581e9e3441adbb0d628832f7dc4574a77a382973ce22911b7e4df2a9d2c693826bbd125bc',1);
/*!40000 ALTER TABLE `Usuario` ENABLE KEYS */;
UNLOCK TABLES;


USE `moto10racingHBT`;

DELIMITER $$
USE `moto10racingHBT`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `moto10racingHBT`.`actStockProductoFromDetalleCompra`
BEFORE INSERT ON `moto10racingHBT`.`detalleCompra`
FOR EACH ROW
begin
declare stockActualCpa INT;
set @stockActualCpa = (select stockProducto from producto where idProducto = new.idProducto);
update Producto
set stockProducto = @stockActualCpa+new.unidadesCompradas where idProducto = new.idProducto;
end$$

USE `moto10racingHBT`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `moto10racingHBT`.`actValorCpaProductoFromDetalleCompra`
BEFORE INSERT ON `moto10racingHBT`.`detalleCompra`
FOR EACH ROW
begin
update Producto
set valorCompraProducto = new.valorCompraProducto where idProducto = new.idProducto;
end$$

USE `moto10racingHBT`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `moto10racingHBT`.`actValorVtaProductoFromDetalleCompra`
BEFORE INSERT ON `moto10racingHBT`.`detalleCompra`
FOR EACH ROW
begin
update Producto
set valorVentaProducto = new.valorVentaProducto where idProducto = new.idProducto;
end$$

USE `moto10racingHBT`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `moto10racingHBT`.`actStockProductoFromDetalleVenta`
BEFORE INSERT ON `moto10racingHBT`.`detalleVenta`
FOR EACH ROW
begin
declare stockActualVta INT;
set @stockActualVta = (select stockProducto from producto where idProducto = new.idProducto);
update Producto
set stockProducto = @stockActualVta-new.unidadesVendidas where idProducto = new.idProducto;
end$$

DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
