package m10r.model;
// Generated Jul 1, 2018 11:19:14 PM by Hibernate Tools 4.3.1



/**
 * UbicacionProducto generated by hbm2java
 */
public class UbicacionProducto  implements java.io.Serializable {


     private Integer idUbicacionProducto;
     private String descripcionUbicacionPro;
     
     @Override
    public String toString() {
        return String.format("%s{idUbicacionProducto=%d}", getClass().getSimpleName(), getIdUbicacionProducto());
    }   

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + this.idUbicacionProducto;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UbicacionProducto other = (UbicacionProducto) obj;
        if (this.idUbicacionProducto != other.idUbicacionProducto) {
            return false;
        }
        return true;
    }

    public UbicacionProducto() {
    }

    public UbicacionProducto(String descripcionUbicacionPro) {
       this.descripcionUbicacionPro = descripcionUbicacionPro;
    }
   
    public Integer getIdUbicacionProducto() {
        return this.idUbicacionProducto;
    }
    
    public void setIdUbicacionProducto(Integer idUbicacionProducto) {
        this.idUbicacionProducto = idUbicacionProducto;
    }
    public String getDescripcionUbicacionPro() {
        return this.descripcionUbicacionPro;
    }
    
    public void setDescripcionUbicacionPro(String descripcionUbicacionPro) {
        this.descripcionUbicacionPro = descripcionUbicacionPro;
    }




}


