package m10r.model;
// Generated Jul 1, 2018 11:19:14 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String userEmp;
     private String passEmp;
     private int idEmpleado;

    public Usuario() {
    }

    public Usuario(int idUsuario, String userEmp, String passEmp, int idEmpleado) {
       this.idUsuario = idUsuario;
       this.userEmp = userEmp;
       this.passEmp = passEmp;
       this.idEmpleado = idEmpleado;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUserEmp() {
        return this.userEmp;
    }
    
    public void setUserEmp(String userEmp) {
        this.userEmp = userEmp;
    }
    public String getPassEmp() {
        return this.passEmp;
    }
    
    public void setPassEmp(String passEmp) {
        this.passEmp = passEmp;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }




}


